### ISSUE TITLE
Android 10 BdUncaughtExceptionHandler throwable:java.lang.reflect.UndeclaredThrowableException  at $Proxy36.bindIsolatedService(Unknown Source)

### ISSUE THREAD

**Issue by ghost** [ALEX5402/NewBlackbox-old#5]
com.vspace                           E  BdUncaughtExceptionHandler throwable:java.lang.reflect.UndeclaredThrowableException
                                                                                                    	at $Proxy36.bindIsolatedService(Unknown Source)
                                                                                                    	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1863)
                                                                                                    	at android.app.ContextImpl.bindIsolatedService(ContextImpl.java:1796)
                                                                                                    	at android.content.ContextWrapper.bindIsolatedService(ContextWrapper.java:717)
                                                                                                    	at android.content.ContextWrapper.bindIsolatedService(ContextWrapper.java:717)
                                                                                                    	at Sx.b(chromium-TrichromeWebViewGoogle.apk-stable-410410683:1)
                                                                                                    	at sy.a(chromium-TrichromeWebViewGoogle.apk-stable-410410683:2)
                                                                                                    	at wy.a(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3)
                                                                                                    	at wy.i(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3)
                                                                                                    	at cy.c(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3)
                                                                                                    	at YD.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410683:6)
                                                                                                    	at mD.run(chromium-TrichromeWebViewGoogle.apk-stable-410410683:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.vcore.fake.service.IActivityManagerProxy$BindService.hook(IActivityManagerProxy.java:261)
                                                                                                    	at com.vcore.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:113)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy36.bindIsolatedService(Unknown Source) 
                                                                                                    	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1863) 
                                                                                                    	at android.app.ContextImpl.bindIsolatedService(ContextImpl.java:1796) 
                                                                                                    	at android.content.ContextWrapper.bindIsolatedService(ContextWrapper.java:717) 
                                                                                                    	at android.content.ContextWrapper.bindIsolatedService(ContextWrapper.java:717) 
                                                                                                    	at Sx.b(chromium-TrichromeWebViewGoogle.apk-stable-410410683:1) 
                                                                                                    	at sy.a(chromium-TrichromeWebViewGoogle.apk-stable-410410683:2) 
                                                                                                    	at wy.a(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3) 
                                                                                                    	at wy.i(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3) 
                                                                                                    	at cy.c(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3) 
                                                                                                    	at YD.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410683:6) 
                                                                                                    	at mD.run(chromium-TrichromeWebViewGoogle.apk-stable-410410683:6) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                                    	at android.os.Looper.loop(Looper.java:219) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: java.lang.SecurityException: BIND_EXTERNAL_SERVICE required for ComponentInfo{com.google.android.webview/org.chromium.content.app.SandboxedProcessService0}
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2091)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2059)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2007)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.bindIsolatedService(IActivityManager.java:5486)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.vcore.fake.service.IActivityManagerProxy$BindService.hook(IActivityManagerProxy.java:261) 
                                                                                                    	at com.vcore.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:113) 
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
                                                                                                    	at $Proxy36.bindIsolatedService(Unknown Source) 
                                                                                                    	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1863) 
                                                                                                    	at android.app.ContextImpl.bindIsolatedService(ContextImpl.java:1796) 
                                                                                                    	at android.content.ContextWrapper.bindIsolatedService(ContextWrapper.java:717) 
                                                                                                    	at android.content.ContextWrapper.bindIsolatedService(ContextWrapper.java:717) 
                                                                                                    	at Sx.b(chromium-TrichromeWebViewGoogle.apk-stable-410410683:1) 
                                                                                                    	at sy.a(chromium-TrichromeWebViewGoogle.apk-stable-410410683:2) 
                                                                                                    	at wy.a(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3) 
                                                                                                    	at wy.i(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3) 
                                                                                                    	at cy.c(chromium-TrichromeWebViewGoogle.apk-stable-410410683:3) 
                                                                                                    	at YD.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410683:6) 
                                                                                                    	at mD.run(chromium-TrichromeWebViewGoogle.apk-stable-410410683:6) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:900) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                                                    	at android.os.Looper.loop(Looper.java:219) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActiveServices.retrieveServiceLocked(libmapleservices.so:6915804)
                                                                                                    	at com.android.server.am.ActiveServices.bindServiceLocked(libmapleservices.so:6890344)
                                                                                                    	at com.android.server.am.ActivityManagerService.bindIsolatedService(libmapleservices.so:6898912)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(libmapleframework.so:6194204)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(libmapleservices.so:7816348)

**Comment by 8763232** [comment]
Because the webview control is used
I also encountered this problem. Is there any solution?

**Comment by ALEX5402** [comment]
it fixed on new release https://github.com/ALEX5402/NewBlackbox/releases
